[project]
name = "contextos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "nltk>=3.9.2",
    "sentence-transformers>=5.1.2",
]
